### PR TITLE
fix: amend content

### PR DESCRIPTION
**Pull request by sarahdayan**
This PR fixes typos and rephrases some sentences.

There are some questions as comments right in the PR.

### CODE REVIEW

**Comment by sarahdayan** [comment]
@ElPicador Looks like there's a [missing configuration file for CircleCI](https://circleci.com/gh/algolia/kubernetes-hands-on/9), thus the tests are marked as failing.

**Comment by ElPicador** [comment]
It is on [`master`](https://github.com/algolia/kubernetes-hands-on/tree/master/.circleci). Did you rebase your PR on the `master` branch?

**Comment by sarahdayan** [comment]
Done @ElPicador looks like all is well 🙂

**Comment by ElPicador** [comment]
\o/
Thanks @sarahdayan, merging!

**Pull request merged**
